name: Ubuntu Clang Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Show environment
        run: |
          lsb_release -a
          cmake --version
          clang++-15 --version

      - name: Configure
        run: |
          cmake -S . -B build \
            -DCMAKE_CXX_COMPILER=clang++-15 \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release